version: "3.7"

services:
  prometheus:
    build:
      context: ./prometheus/
    ports:
      - "127.0.0.1:9090:9090"
    healthcheck:
      test: "exit 0"
      timeout: 10s
      retries: 3
  helloworld:
    build:
      context: .
    ports:
      - "127.0.0.1:8080:8080"
      